import Head from 'next/head';
import Image from "next/image";
import {
    AiFillTwitter,
    AiFillLinkedin,
    AiFillYoutube,
    AiFillTwitterCircle,
    AiFillFacebook,
    AiFillInstagram,
    
} from "react-icons/ai";
import {BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import deved1 from "../public/davou/davou.jpg"
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import pic1 from "../public/davou/ayra-star.jpg";
import pic2 from "../public/davou/five-alive.jpg";
import pic3 from "../public/davou/don-royal.jpg";
import pic4 from "../public/davou/malta.jpg";
import pic5 from "../public/davou/black-label.jpg";
import pic6 from "../public/davou/coke.jpg";





export default function Home() {
    const [darkMode, setDarkMode] = useState(false);

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>DAVOU MUSA GYANG</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                
            </Head>
            <main className="px-10 bg-white dark:bg-gray-900 md:px-20 lg:px-40">
                <section className="min-h-screen">
                    <nav className="flex justify-between py-10 mb-12 dark:text-white">
                        <h1 className="text-xl font-burtons">developed by kanweitech</h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill 
                                    onClick={() => setDarkMode(!darkMode)}
                                    className="text-2xl cursor-pointer"
                                />
                            </li>
                                <a
                                 className="px-4 py-2 ml-8 text-white border-none rounded-md bg-gradient-to-r from-cyan-500 text- to-teal-500"
                                 href="#"
                                >Resume
                                </a>
                        </ul>
                    </nav>
                    <div className="p-10 py-10 text-center">
                        <h2 className="py-2 text-5xl font-medium text-teal-600 dark:text-teal-400 md:text-6xl">DAVOU MUSA GYANG</h2>
                        <h3 className="py-2 text-2xl dark:text-white md:text-3xl">Packs Specialist.</h3>
                        <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md;text-xl">A Professional product packs specialist and art director.</p>
                    </div>
                    <div className="flex justify-center gap-16 py-3 text-5xl text-gray-600 dark:text-gray-400">
                        <AiFillYoutube />
                        <AiFillFacebook/>
                        <AiFillInstagram/>
                    </div>

                    <div className="relative mx-auto mt-20 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 w-80 md:h-96 md:w-96">
                        <Image src={deved1} alt="" layout="fill" objectFit="cover" />
                    </div>
                </section>

                <section>

                    {/* Services I offer:

I am product and packs specialist based in Lagos Nigeria with vast experience in different product shots and mock up packs, special pouring shots with different rigs and hand methods. 
 I have worked with internationally reputable brands among which are; Coca Cola, Guinness, Jonny Walker, Nestle, Cadbury, etc.. 

My Jobs are presently airing both on Tv and social media platforms across Africa. Notably are, Fanta campaign for Pan Africa and the rest of Africa, Nestle Nescafé airing in 7 African countries ( Ghana, Nigeria, Angola, Burkina Faso, Cote Di Voire, Senegal, Guinea).
Coke Studio Africa featuring Mayokun, Buju, Yung Stunna, Nikita, Kahligraph Jones. These are artists from Nigeria, South Africa and Kenya. */}
                    <div>
                        <h3 className="py-1 text-3xl dark:text-white">Services I offer</h3>
                        <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">I am product and packs specialist based in Lagos Nigeria with vast experience in different product shots and mock up packs, special pouring shots with different rigs and hand methods. 
                        I have worked with internationally reputable brands among which are; <span className="text-teal-500">Coca Cola, Guinness, Jonny Walker, Nestle, Cadbury, etc.. </span> My Jobs are presently airing both on Tv and social media platforms across Africa. Notably are, Fanta campaign for Pan Africa and the rest of Africa, Nestle Nescafé airing in 7 African countries ( Ghana, Nigeria, Angola, Burkina Faso, Cote Di Voire, Senegal, Guinea).
                        Coke Studio Africa featuring <span className="text-teal-500"> Mayokun, Buju, Yung Stunna, Nikita, Kahligraph Jones</span>. These are artists from Nigeria, South Africa and Kenya, and collaborated with talented people to create digital products for both business and consumer use.
                            
                        </p>
                        <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">
                            I offer from wide range of services, including brand design, programming and teaching.
                        </p>
                    </div>

                    <div className="gap-10 lg:flex">
                        <div className="flex-1 p-10 my-10 text-center shadow-lg rounded-xl dark:bg-white">
                            <Image src={design} width={100} height={100} alt="design"/>
                            <h3 className="pt-8 pb-2 text-lg font-medium">Beautiful Designs</h3>
                            <p className="py-2">
                                Creating elegant designs suited for your needs following core design theory
                            </p>
                            <h4 className="py-8 text-teal-600">Design Tools I need</h4>
                            <p className="py-1 text-gray-800">Photoshop</p>
                            <p className="py-1 text-gray-800">Illustrator</p>
                            <p className="py-1 text-gray-800">Figma</p>
                            <p className="py-1 text-gray-800">Indesign</p>
                        </div>
                        <div className="flex-1 p-10 my-10 text-center shadow-lg rounded-xll dark:bg-white">

                            <Image src={code} width={100} height={100} alt="code"/>
                            <h3 className="pt-8 pb-2 text-lg font-medium">
                                Code your dream project
                            </h3>
                            <p className="py-2">
                                Do you have an idea for your next great website? Let's make it a reality.
                            </p>
                            <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                            <p className="py-1 text-gray-800">Photoshop</p>
                            <p className="py-1 text-gray-800">Illustrator</p>
                            <p className="py-1 text-gray-800">Figma</p>
                            <p className="py-1 text-gray-800">Indesign</p>
                        </div>
                        <div className="flex-1 p-10 my-10 text-center shadow-lg rounded-xl dark:bg-white">
                            <Image src={consulting} width={100} height={100} alt="consulting" />
                            <h3 className="pt-8 pb-2 text-lg font-medium ">Consulting</h3>
                            <p className="py-2">
                                Are you interested in feedback for your current project? I can
                                give you tips and tricks to level it up.
                            </p>
                            <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                            <p className="py-1 text-gray-800">Photoshop</p>
                            <p className="py-1 text-gray-800">Illustrator</p>
                            <p className="py-1 text-gray-800">Figma</p>
                            <p className="py-1 text-gray-800">Indesign</p>
                        </div>
                    </div>
                </section>
                <section className="py-10">
                    <div>
                        <h3 className="py-1 text-3xl dark:text-white ">Portofolio</h3>
                        <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">
                            Since the beginning of my journey as a freelance designer and
                            developer, I've done remote work for
                            <span className="text-teal-500"> agencies </span>
                            consulted for <span className="text-teal-500">startups </span>
                            and collaborated with talanted people to create digital products
                            for both business and consumer use.
                        </p>
                        <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">
                            I offer from a wide range of services, including brand design,
                            programming and teaching.
                        </p>
                    </div>
                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                            <div className="flex-1 basis-1/3 ">
                                <Image
                                    className="object-cover rounded-lg"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={pic1}
                                    alt="pic1"
                                />
                            </div>
                            <div className="flex-1 basis-1/3">
                                <Image
                                    className="object-cover rounded-lg"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={pic2}
                                    alt="pic2"
                                />
                            </div>
                            <div className="flex-1 basis-1/3">
                                <Image
                                    className="object-cover rounded-lg"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={pic3}
                                    alt="pic3"
                                />
                            </div>
                            <div className="flex-1 basis-1/3">
                                <Image
                                    className="object-cover rounded-lg"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={pic4}
                                    alt="pic4"
                                />
                            </div>
                            <div className="flex-1 basis-1/3">
                                <Image
                                    className="object-cover rounded-lg"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={pic5}
                                    alt="pic5"
                                />
                            </div>
                            <div className="flex-1 basis-1/3">
                                <Image
                                    className="object-cover rounded-lg"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={pic6}
                                    alt="pic6"
                                />
                            </div>
                    </div>
                </section>
            </main>

        </div>

    );
}